[[language]]
name = "nix"
auto-format = true
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
comment-token = "#"
language-servers = [ "nil" ]
indent = { tab-width = 2, unit = "  " }
formatter = {command = 'alejandra', args = ["-q"]}

[[language]]
name = "python"
auto-format = true
# formatter = {command = 'ruff', args = ["--quiet", "-"]}
language-servers = ["ruff-lsp"]
roots = ["pyproject.toml"]

[language-server.ruff-lsp]
command = "ruff-lsp"
config = {settings = {run = "onSave"}}

[[language]]
name = "mx3"
grammar = "go"
scope = "source.mx3"
injection-regex = "mx3"
file-types = ["mx3"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []

[[grammar]]
name = "mx3"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }


